# I/O Parameters

train_data_dir: "/scratch/speaker_databases/VoxCeleb-2/dev"
valid_data_dir: "/scratch/speaker_databases/VoxSRC2023/dev"
train_labels_path: "labels/sc_labels.ndx"
valid_clients: "labels/2023_val_clients.ndx"
valid_impostors: "labels/2023_val_impostors.ndx"
out_dir: "./models/resnet34_first_try"
model_name: "CNN"
requeue: False

# Augmentation Parameters

augmentation_data_dir: "/scratch/speaker_databases/musan"
augmentation_labels_path: "labels/musan.lst"
augmentation_prob: 0.75 # Probability of applying augmentation to a sample. 0 means no augmentation.

# Network Parameters

front_end: "ResNet34"
window_size: 3.5
kernel_size: 1024
embedding_size: 400
heads_number: 32
pooling_method: "DoubleMHA"
mask_prob: 0.3

# AMSoftmax Config

scalingFactor: 30.0
marginFactor: 0.4

# Optimization

optimizer: "Adam"
learning_rate: 0.0001
weight_decay: 0.001
batch_size: 32
gradientAccumulation: 4
max_epochs: 500
early_stopping: 25
num_workers: 2

# Logging
print_metric_window: 1000
