train_data_dir: /home/usuaris/scratch/speaker_databases/VoxCeleb-2/dev
valid_data_dir: /home/usuaris/scratch/speaker_databases/VoxSRC2023/dev
train_labels_path: labels/sc_labels.ndx
valid_clients: labels/2023_val_clients.ndx
valid_impostors: labels/2023_val_impostors.ndx
out_dir: models/resnet34_75prob_MHA_8_AttActivation
model_name: CNN
requeue: false
augmentation_data_dir: /home/usuaris/scratch/speaker_databases/musan
rirs_data_dir: /home/usuaris/scratch/speaker_databases/RIRS_NOISES
augmentation_labels_path: labels/musan_labels.lst
rirs_labels_path: labels/rirs.lst
augmentation_prob: 0.75
front_end: ResNet34
activation: Attention
window_size: 3.5
kernel_size: 512
embedding_size: 400
heads_number: 8
pooling_method: MHA
mask_prob: 0.25
scalingFactor: 30.0
marginFactor: 0.4
optimizer: Adam
learning_rate: 0.0001
weight_decay: 0.001
batch_size: 64
gradientAccumulation: 2
max_epochs: 500
early_stopping: 25
num_workers: 4
scheduler_lr_epochs: 5
scheduler_lr_gamma: 0.5
print_metric_window: 1000
num_spkrs: 5964
